name: Run Bot

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: إعداد الوظيفة
        uses: actions/checkout@v3

      - name: إعداد بايثون 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: تثبيت التبعيات
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/cleitonleonel/pyquotex.git
          pip install -r requirements.txt

      - name: تشغيل البوت
        run: |
          python3 bot.py
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          PING_INTERVAL: 20
