name: Run Bot

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: تثبيت التبعيات
        run: |
          pip install --upgrade pip
          pip install pyrogram tgcrypto motor colorama dnspython flask gunicorn requests pymongo python-dotenv
          git clone https://github.com/cleitonleonel/pyquotex.git /tmp/pyquotex
          pip install -e /tmp/pyquotex

      - name: إنشاء ملف env
        run: |
          echo "API_ID=${{ secrets.API_ID }}" > .env
          echo "API_HASH=${{ secrets.API_HASH }}" >> .env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo "OWNER_ID=${{ secrets.OWNER_ID }}" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "PING_INTERVAL=20" >> .env

      - name: تشغيل البوت
        run: python3 bot.py
